### ISSUE TITLE
Convert role from using 'host: all' to 'hosts: localhost' to help avoid race conditions, higher I/O when targeting a local system

### ISSUE THREAD

**Issue by atc0005** [atc0005/ansible-role-lxd-testenv#5]
## Overview

The current role assumes that it is processing a list of hosts instead of running against localhost. When mass-installing packages or performing disk intensive operations this could delay the spin-up or tear-down time needed.

More than that however, the workarounds to prevent race conditions when updating `$HOME/.ssh/known_hosts` and `/etc/hosts` are already serializing those tasks, so explicitly updating the role to handle hosts in a serialized batch internally seems to make more sense.

## TODO

- [x] **Default**: lxd-setup playbook properly creates new containers with desired settings
- [x] **Default**: lxd-remove playbook properly tears down containers and remove settings from host

- [x] Confirm that the default state of the `default/main.yml` flags work as expected
    - [x] lxd_host_update_ssh_client_user_config_file
    - [x] lxd_host_update_ssh_client_system_config_file
    - [x] lxd_host_update_user_known_hosts_file
    - [x] lxd_host_update_system_known_hosts_file
    - [x] lxd_host_update_etc_hosts_file
    - [x] lxd_host_remove_container_settings
    - [x] lxd_host_remove_containers
    - [x] lxd_containers_update_hosts_file
    - [x] lxd_containers_proxy_server
    - [x] lxd_containers_add_proxy_to_etc_environment_file
    - [x] lxd_containers_create
    - [x] lxd_containers_bootstrap
    - [x] lxd_containers_configure
    - [x] lxd_containers_docker_storage_driver

- [x] Confirm that setting flags in playbook works as expected
    - [x] lxd_host_update_ssh_client_user_config_file
    - [x] lxd_host_update_ssh_client_system_config_file
    - [x] lxd_host_update_user_known_hosts_file
    - [x] lxd_host_update_system_known_hosts_file
    - [x] lxd_host_update_etc_hosts_file
    - [x] lxd_host_remove_container_settings
    - [x] lxd_host_remove_containers
    - [x] lxd_containers_update_hosts_file
    - [x] lxd_containers_proxy_server
    - [x] lxd_containers_add_proxy_to_etc_environment_file
    - [x] lxd_containers_create
    - [x] lxd_containers_bootstrap
    - [x] lxd_containers_configure
    - [x] lxd_containers_docker_storage_driver

- [x] Update documentation to reflect new options
- [x] Update documentation to mark deprecated options (note: there may not be any)

**Comment by atc0005** [comment]
My eyes are glazing over, but I believe I've managed to check expected combinations of settings. Further testing and validation can be applied as part of a future development effort.

**Comment by atc0005** [comment]
Included in #14.
